DROP TABLE IF EXISTS fetch_history CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS chats CASCADE;
DROP TABLE IF EXISTS user_preferences CASCADE;
DROP TABLE IF EXISTS api_config CASCADE;
DROP TABLE IF EXISTS news CASCADE;
DROP TABLE IF EXISTS news_sources CASCADE;
DROP TABLE IF EXISTS news_category CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE IF NOT EXISTS users (id SERIAL PRIMARY KEY, username TEXT NOT NULL UNIQUE, hashed_password TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_users_username ON users (username);
CREATE TABLE IF NOT EXISTS news_category (id SERIAL PRIMARY KEY, name TEXT NOT NULL, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, UNIQUE (name, user_id));
CREATE TABLE IF NOT EXISTS news_sources (id SERIAL PRIMARY KEY, name TEXT NOT NULL, url TEXT NOT NULL, category_id INTEGER NOT NULL REFERENCES news_category(id) ON DELETE CASCADE, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, UNIQUE (url, user_id), UNIQUE (name, user_id));
CREATE INDEX IF NOT EXISTS idx_news_sources_url ON news_sources (url);
CREATE TABLE IF NOT EXISTS news (id BIGSERIAL PRIMARY KEY, title TEXT NOT NULL, url TEXT NOT NULL, source_name TEXT, category_name TEXT, source_id INTEGER REFERENCES news_sources(id) ON DELETE SET NULL, category_id INTEGER REFERENCES news_category(id) ON DELETE SET NULL, summary TEXT, analysis TEXT, date TEXT, content TEXT, top_image TEXT, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, task_group_id TEXT, UNIQUE (url, user_id));
CREATE INDEX IF NOT EXISTS idx_news_url ON news (url);
CREATE INDEX IF NOT EXISTS idx_news_date ON news (date DESC);
CREATE INDEX IF NOT EXISTS idx_news_category_id ON news (category_id);
CREATE INDEX IF NOT EXISTS idx_news_source_id ON news (source_id);
CREATE INDEX IF NOT EXISTS idx_news_user_id ON news (user_id);
CREATE INDEX IF NOT EXISTS idx_news_user_id_created_at ON news (user_id, created_at DESC);
CREATE TABLE IF NOT EXISTS api_config (id SERIAL PRIMARY KEY, model TEXT NOT NULL, base_url TEXT NOT NULL, api_key TEXT NOT NULL, context INTEGER, max_output_tokens INTEGER, description TEXT, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, created_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, modified_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS user_preferences (config_key TEXT NOT NULL, config_value TEXT, description TEXT, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, PRIMARY KEY (config_key, user_id));
CREATE TABLE IF NOT EXISTS chats (id BIGSERIAL PRIMARY KEY, title TEXT NOT NULL, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS messages (id BIGSERIAL PRIMARY KEY, chat_id BIGINT NOT NULL REFERENCES chats(id) ON DELETE CASCADE, sender TEXT NOT NULL, content TEXT, timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, sequence_number INTEGER);
CREATE INDEX IF NOT EXISTS idx_messages_chat_id_sequence ON messages (chat_id, sequence_number);
CREATE TABLE IF NOT EXISTS fetch_history (id BIGSERIAL PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, source_id INTEGER NOT NULL REFERENCES news_sources(id) ON DELETE CASCADE, record_date DATE NOT NULL, items_saved_today INTEGER DEFAULT 0, last_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, last_batch_task_group_id TEXT, UNIQUE (user_id, source_id, record_date));
CREATE INDEX IF NOT EXISTS idx_fetch_history_user_id ON fetch_history (user_id);
CREATE INDEX IF NOT EXISTS idx_fetch_history_source_id ON fetch_history (source_id);
CREATE INDEX IF NOT EXISTS idx_fetch_history_date ON fetch_history (record_date);
CREATE INDEX IF NOT EXISTS idx_news_search_fts ON news USING GIN (to_tsvector('simple', COALESCE(title, '') || ' ' || COALESCE(summary, '') || ' ' || COALESCE(source_name, '') || ' ' || COALESCE(category_name, '')));